/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    Library classUnderTest = new Library();
    @Test
    public void testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testAddNumbers() {
        int ans = classUnderTest.addNumbers(4, 5);
        assertTrue("Should == 9", ans == 9);
    }
}
