/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int addNumbers(int i, int i1) {
        return i + i1;
    }
}
